- name: Minikube
  hosts: localhost
  become: true

  vars_files:
    - ../../vars/main.yml

  vars:
    arch: "{{ [ansible_architecture] | map('extract', deb_architecture) | first }}"
    minikube_release: "minikube-linux-{{ arch }}"
    minikube_link: "https://storage.googleapis.com/minikube/releases/latest/{{ minikube_release }}"
    minikube_install_path: /usr/local/bin/minikube
    public_directory: "{{ instance.public_directory }}"

  pre_tasks:
    - name: Download minikube binary
      ansible.builtin.shell: "curl -LO {{ minikube_link }}"
      args:
        chdir: "{{ public_directory }}"

  tasks:
    - name: Install minukube
      ansible.builtin.shell: "install minikube-linux-amd64 {{ minikube_install_path }}"
      args:
        chdir: "{{ public_directory }}"
