- name: Pulumi
  hosts: localhost
  become: true

  vars_files:
    - ../../vars/main.yml

  vars:
    pulumi_link: https://get.pulumi.com
    pulumi_installer: pulumi-cli.sh
    public_directory: "{{ instance.public_directory }}"
    pulumi_installer_path: "{{ public_directory }}/{{ pulumi_installer }}"
    user: "{{ instance.user.name }}"
    home: "/{{ instance.user.home }}/{{ user }}"
    pulumi_installer_home_path: "{{ home }}/{{ pulumi_installer }}"
    pulumi_bin_path: "{{ home }}/.pulumi/bin"

  pre_tasks:
    - name: Download pulumi cli
      ansible.builtin.shell:
        chdir: "{{ public_directory }}"
        cmd: "curl -fsSL {{ pulumi_link }} --output {{ pulumi_installer }}"

    - name: Allow installer to be executable
      ansible.builtin.file:
        path: "{{ pulumi_installer_path }}"
        group: sudo
        mode: '0770'

    - name: Copy pulumi installer to user home
      ansible.builtin.copy:
        src: "{{ pulumi_installer_path }}"
        dest: "{{ pulumi_installer_home_path }}"
        owner: "{{ user }}"
        mode: "0770"
        group: sudo

    - name: Install dependency needed to set permissions as a local user
      ansible.builtin.apt:
        name: acl
        update_cache: true

  tasks:
    - name: Install pulumi cli as local user
      become: true
      become_user: "{{ user }}"
      ansible.builtin.shell:
        chdir: "{{ home }}"
        cmd: "./{{ pulumi_installer }}"
  
  post_tasks:
    - name: Add pulumi to local user path
      ansible.builtin.blockinfile:
        path: "{{ home }}/.profile"
        backup: true
        create: true
        block: |
          export PATH="{{ pulumi_bin_path }}:$PATH"

    - name: Remove the installer from user home
      ansible.builtin.file:
        path: "{{ pulumi_installer_home_path }}"
        state: absent