- name: Common utilities
  hosts: localhost
  become: true
  
  tasks:
    - name: Install general utilities
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - net-tools
        - build-essential
        - procps
        - file
        - bash-completion
        - tree
        - netcat