- name: User
  hosts: localhost
  become: true

  vars_files:
    - "../../vars/main.yml"
  vars:
    user: "{{ instance.user.name }}"
    home: "/{{ instance.user.home }}/{{ user }}"
    password: "{{ instance.user.password }}"
    ansible_staging_directory: "{{ instance.ansible.staging_directory }}"
    public_directory: "{{ instance.public_directory }}"

  pre_tasks:
    - name: Install dependency
      ansible.builtin.apt:
        name: whois
        update_cache: yes

    - name: Generate password
      ansible.builtin.shell:
        cmd: "echo -n {{ password }} | mkpasswd --method=sha-512 --stdin"
      register: hashed_password

  tasks:
    - name: Create user
      ansible.builtin.user:
        name: "{{ user }}"
        append: yes
        groups: sudo
        home: "{{ home }}"
        shell: /bin/bash
        password: "{{ hashed_password.stdout }}"
      register: create_user_output