Cloud: aws
AWS:
  AccessKeyId: 234sadfgddsdadfgd3ASF&/(%)
  SecretAccessKey: SDFGSDF45DDDFG3
  IAmProfile: DSDDFDGSFD
  UserIds:
    - 2342342x
    - b34234
  Region: us-east-2
  EC2:
    Instance:
      Type: t3a.large
    Volume:
      Type: gp2
      Size: 13
AMI:
  Name: test
  Base:
    Filter: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20230516
    User: ubuntu
    RootDeviceType: ebs
    VirtualizationType: hvm
    Owners:
      - a
      - b
  User: dev
  Home: home
  Password: test12345
  Tools:
    - aws
    - docker
Git:
  Username: Eduardo Casanova
  Email: ed.wacc1995@gmail.com
GitHub:
  PersonalAccessTokenClassic: asfa4sdfgd34
Pulumi:
  PersonalAccessToken: safda3432545
Up:
  AMI_Id: asfasf3w4sf