AWS:
  AccessKeyId: ""
  SecretAccessKey: ""
  IAmProfile: ""
  UserIds:
    - a
    - b
  Region: ""
  EC2:
    Instance:
      Type: t3a.large
    Volume:
      Type: gp2
      Size: 13
AMI:
  Name: test
  Base:
    Filter: "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20230516"
    User: "ubuntu"
    RootDeviceType: "ebs"
    VirtualizationType: "hvm"
    Owners:
      - a
      - b
  User: dev
  Home: home
  Password: test12345
  Tools:
    - aws
    - docker
Git:
  Username: Eduardo Casanova
  Email: ed.wacc1995@gmail.com
GitHub:
  PersonalAccessTokenClassic: ""
Pulumi:
  PersonalAccessToken: ""
Up:
  AMI_Id: ""