- name: Rust
  hosts: localhost
  become: true

  vars_files:
    - ../../vars/main.yml
  vars:
    public_directory: "{{ instance.public_directory }}"
    user: "{{ instance.user.name }}"
    home: "/{{ instance.user.home }}/{{ user }}"
    rustup_init_url: "https://sh.rustup.rs"
    rustup_init_installer: rustup.sh
    rustup_init_installer_path: "{{ public_directory }}/{{ rustup_init_installer }}"
    rustup_init_user_home_path: "{{ home }}/{{ rustup_init_installer }}"

  pre_tasks:
    - name: Install dependency
      ansible.builtin.apt:
        name: acl
        update_cache: yes

    - name: Download installer
      ansible.builtin.shell: "curl --proto '=https' --tlsv1.2 -sSf -o {{ rustup_init_installer }} {{ rustup_init_url }}"
      args:
        chdir: "{{ public_directory }}"

    - name: Copy the installer to user home
      ansible.builtin.copy:
        src: "{{ rustup_init_installer_path }}"
        dest: "{{ rustup_init_user_home_path }}"
        owner: "{{ user }}"
        mode: "0770"
        group: sudo

  tasks:
    - name: Install rust
      become: true
      become_user: "{{ user }}"
      ansible.builtin.shell: "./{{ rustup_init_installer }} -y --profile complete"
      args:
        chdir: "{{ home }}"

  post_tasks:
    - name: Remove installer
      ansible.builtin.file:
        path: "{{ rustup_init_user_home_path }}"
        state: absent

    - name: Install dependency for debugging
      ansible.builtin.apt:
        name: gdb
        update_cache: yes