- name: AWS cli
  hosts: localhost
  become: true

  vars_files:
    - "../../vars/main.yml"

  vars:
    user: "{{ instance.user.name }}"
    home: "/{{ instance.user.home }}/{{ user }}"
    public_directory: "{{ instance.public_directory }}"
    aws_installer_zip: awscliv2.zip
    aws_installer_executable: "{{ public_directory }}/aws/install"
    aws_bin_dir: "/usr/local/bin"
    aws_install_dir: "/usr/local/aws-cli"
    aws_access_key: "{{ aws.access_key }}"
    aws_secret_key: "{{ aws.secret_key }}"
    aws_region: "{{ aws.region }}"
    aws_group: aws

  pre_tasks:
    - name: Install dependency
      ansible.builtin.apt:
        update_cache: true
        name: unzip

    - name: Download aws cli
      ansible.builtin.shell: "curl 'https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip' -o {{ aws_installer_zip }}"
      args:
        chdir: "{{ public_directory }}"
        creates: "{{ aws_installer_zip }}"

    - name: Unzip installer
      ansible.builtin.shell: "unzip -u {{ aws_installer_zip }}"
      args:
        chdir: "{{ public_directory }}"
        creates: "{{ aws_installer_executable }}"
    
    - name: Create aws group
      ansible.builtin.group:
        name: "{{ aws_group }}"
    
    - name: Add local user to group
      ansible.builtin.user:
        name: "{{ user }}"
        groups: "{{ aws_group }}"
        append: true

  tasks:
    - name: Install AWS cli
      ansible.builtin.shell: "{{ aws_installer_executable }} --bin-dir {{ aws_bin_dir }} --install-dir {{ aws_install_dir }}"
      args:
        chdir: "{{ public_directory }}"

    - name: Ensure AWS credentials are present
      ansible.builtin.blockinfile:
        path: "{{ home }}/.aws/credentials"
        create: true
        owner: "{{ user }}"
        group: "{{ user }}"
        backup: true
        mode: "0600"
        block: |
          [default]
          aws_access_key_id={{ aws_access_key }}
          aws_secret_access_key={{ aws_secret_key }}
      no_log: true
  
    - name: Ensure AWS config is present
      ansible.builtin.blockinfile:
        path: "{{ home }}/.aws/config"
        create: true
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0600"
        block: |
          [default]
          region={{ aws_region }}
          output=json
  
  post_tasks:
    - name: Allow local user to run aws cli
      ansible.builtin.file:
        path: "{{ aws_install_dir }}"
        state: directory
        recurse: true
        group: "{{ aws_group }}"
        mode: "0550"