#! Base
- name: Base
  ansible.builtin.import_playbook: playbooks/base/main.yml
  tags:
  - always
## Cloud providers
- name: AWS
  ansible.builtin.import_playbook: playbooks/cloud_providers/aws_cli.yml
  tags:
  - aws
## Containerization
- name: Docker
  ansible.builtin.import_playbook: playbooks/containerization/docker.yml
  tags:
  - docker
## IaC
- name: Pulumi
  ansible.builtin.import_playbook: playbooks/iac/pulumi.yml
  tags:
  - pulumi
## Orchestration
- name: Helm
  ansible.builtin.import_playbook: playbooks/orchestration/helm.yml
  tags:
  - helm
- name: Kubectl
  ansible.builtin.import_playbook: playbooks/orchestration/kubectl.yml
  tags:
  - kubectl
- name: Minikube
  ansible.builtin.import_playbook: playbooks/orchestration/minikube.yml
  tags:
  - minikube
## Programming languages
- name: Dotnet
  ansible.builtin.import_playbook: playbooks/programming_languages/dotnet.yml
  tags:
  - dotnet
- name: Go
  ansible.builtin.import_playbook: playbooks/programming_languages/go.yml
  tags:
  - go
- name: NodeJS
  ansible.builtin.import_playbook: playbooks/programming_languages/node_js.yml
  tags:
  - node_js
- name: Python
  ansible.builtin.import_playbook: playbooks/programming_languages/python.yml
  tags:
  - python
- name: Rust
  ansible.builtin.import_playbook: playbooks/programming_languages/rust.yml
  tags:
  - rust
## Terminal
- name: Starship
  ansible.builtin.import_playbook: playbooks/terminal/starship.yml
  tags:
  - starship
# ## Vc
# - name: GitHub
#   ansible.builtin.import_playbook: ./vc/git_hub.yml
#   tags:
#   - github