- name: NodeJS
  hosts: localhost
  become: true

  vars_files:
    - ../../vars/main.yml

  vars:
    user: "{{ instance.user.name }}"
    home: "/{{ instance.user.home }}/{{ user }}"
    public_directory: "{{ instance.public_directory }}"
    nvm_installer_link: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh
    nvm_installer: nvm_install.sh
    nvm_installer_path: "{{ public_directory }}/{{ nvm_installer }}"
    nvm_installer_user_home_path: "{{ home }}/{{ nvm_installer }}"

  pre_tasks:
    - name: Download nvm
      ansible.builtin.shell: "curl -o {{ nvm_installer }} {{ nvm_installer_link }}" 
      args:
        chdir: "{{ public_directory }}"
    
    - name: Make the installer executable
      ansible.builtin.file:
        path: "{{ nvm_installer_path }}"
        group: sudo
        mode: "0770"

    - name: Copy installer to local user home
      ansible.builtin.copy:
        src: "{{ nvm_installer_path }}"
        dest: "{{ nvm_installer_user_home_path }}"
        owner: "{{ user }}"
        mode: "0770"
        group: sudo

    - name: Install dependency needed to set permissions as a local user
      ansible.builtin.apt:
        name: acl
        update_cache: true

  tasks:
    - name: Install nvm
      become: true
      become_user: "{{ user }}"
      ansible.builtin.shell: "./{{ nvm_installer }}"
      args:
        chdir: "{{ home }}"

    - name: Add nvm bash autocompletion
      ansible.builtin.lineinfile:
        path: "{{ home }}/.bashrc"
        backup: true
        create: true
        line: >
          [[ -r $NVM_DIR/bash_completion ]] && \. $NVM_DIR/bash_completion

  post_tasks:
    - name: Remove nvm installer from local user home
      ansible.builtin.file:
        path: "{{ nvm_installer_user_home_path }}"
        state: absent

    - name: Ensure nvm is loaded on non-logging shells
      become: true
      become_user: root
      ansible.builtin.blockinfile:
        path: /etc/profile.d/nvm-autoload.sh
        create: true
        backup: true
        block: |
          if [ -f {{ home }}/.nvm/nvm.sh ]; then
              source {{ home }}/.nvm/nvm.sh
          fi
